{% set name = "sphinx-intl" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4ddc63be820c94e23393538cc3d4c31631acab7001b0052e4530ff5bf623af97

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - sphinx-intl = sphinx_intl.commands:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - babel
    - click
    - python >=3.7
    - setuptools
    - sphinx

test:
  imports:
    - sphinx_intl
  commands:
    - pip check
    - sphinx-intl --help
  requires:
    - pip

about:
  home: https://github.com/sphinx-doc/sphinx-intl
  summary: Sphinx utility that make it easy to translate and to apply translation.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - maresb
