{% set name = "sphinx-intl" %}
{% set version = "2.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx_intl-{{ version }}.tar.gz
  sha256: 04b0d8ea04d111a7ba278b17b7b3fe9625c58b6f8ffb78bb8a1dd1288d88c1c7

build:
  entry_points:
    - sphinx-intl = sphinx_intl.commands:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - setuptools
    - click
    - babel
    - sphinx

test:
  imports:
    - sphinx_intl
  commands:
    - pip check
    - sphinx-intl --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/sphinx-doc/sphinx-intl
  summary: Sphinx utility that make it easy to translate and to apply translation.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sphinx
    - maresb
